### ISSUE TITLE
TaskGroup doesnt work well with assertion libraries like assert and should

### ISSUE THREAD

**Issue by kksharma1618** [bevry/taskgroup#17] opened 2015-02-01 04:19 UTC
Mainly because it suppresses errors from callback.

Code:
``` javascript
var TaskGroup = require('taskgroup').TaskGroup;
var Task = require('taskgroup').Task;
var assert = require('assert');

function toTest(a, next) {
    var tasks = new TaskGroup();
    tasks.addTask('upper case', function(next) {
        a = a.toUpperCase();
        next();
    });
    tasks.done(function(err) {
        next(err, a);
    }).run();
}
function toTestWithoutTaskGroup(a, next) {
    a = a.toUpperCase();
    setTimeout(function() {
        next(null, a);
    }, 10);
}

toTest("abc", function(err, r) {
    assert.equal(r, "lmn");
});

toTestWithoutTaskGroup("abc", function(err, r) {
    assert.equal(r, "efg");
});
```

In above code, only the second assert (toTestWithoutTaskGroup) will report the failure. First assert will still throw the error but TaskGroup suppresses that. Maybe it shouldnt suppress errors in final callback?

**Comment by kksharma1618** [comment] 2015-02-01 04:26
If you call done callback from next tick then it works:

``` javascript
var TaskGroup = require('taskgroup').TaskGroup;
var Task = require('taskgroup').Task;
var assert = require('assert');

function toTest(a, next) {
    var tasks = new TaskGroup();
    tasks.addTask('upper case', function(next) {
        a = a.toUpperCase();
        next();
    });
    tasks.done(function(err) {
        next(err, a);
    }).run();
}
function toTest2(a, next) {
    var tasks = new TaskGroup();
    tasks.addTask('upper case', function(next) {
        a = a.toUpperCase();
        next();
    });
    tasks.done(function(err) {
        setTimeout(function() {
            next(err, a);
        });
    }).run();

}
function toTestWithoutTaskGroup(a, next) {
    a = a.toUpperCase();
    setTimeout(function() {
        next(null, a);
    }, 10);
}

toTest("abc", function(err, r) {
    assert.equal(r, "lmn");
});

toTest2("abc", function(err, r) {
    assert.equal(r, "pqr");
});


toTestWithoutTaskGroup("abc", function(err, r) {
    assert.equal(r, "efg");
});
```

In above code assertion will report failure in toTest2 and toTestWithoutTaskGroup

**Comment by kksharma1618** [comment] 2015-02-01 04:44
If anyone else is facing this issue, here is a quick fix.

Just add this code before your tests:

``` javascript
var TaskGroup = require('taskgroup').TaskGroup;
var Task = require('taskgroup').Task;
if(!TaskGroup.prototype.oldOnceDone) {
    TaskGroup.prototype.oldOnceDone = TaskGroup.prototype.onceDone;
    TaskGroup.prototype.onceDone = function(next) {
        if(typeof(next) != 'function') {
            return this;
        };
        return this.oldOnceDone(function() {
            var args = Array.prototype.slice(arguments);
            setTimeout(function() {
                next.apply(null, args);
            }, 2);
        });
    };
}
```

**Comment by balupton** [comment] 2015-02-01 12:12
Thanks for the report. I wonder if that quick fix will still pass the TaskGroup test suite?

**Comment by kksharma1618** [comment] 2015-02-01 13:21
I forked and updated whenDone, onceDone: https://github.com/kksharma1618/taskgroup/commit/dd079a71423decb10e2f76810d6d21d8737333d2

Test failed: https://www.dropbox.com/s/z2o8v6wp7nuq59w/Screenshot%202015-02-01%2018.46.13.png?dl=0

**Comment by balupton** [comment] 2015-02-01 14:28
Yeah, so nextTick won't work. I wonder if it is due to the `domain` catching the callback when it shouldn't. I wonder if we can close the domain before the done callback is called, or if we can set the boundaries of the domain better.

**Comment by kksharma1618** [comment] 2015-02-01 14:36
Well, I think that test failed because completion state of task group wasnt set properly when assert was done. Results were same in both actual and expected values, only difference was completed tasks count.

**Comment by balupton** [comment] 2015-02-01 14:38
Running your original code, this is the output I get:

```
$ node issue17.js 

Error: The task [taskgroup 0.11598217790015042 ➞  upper case] just completed, but it had already completed earlier, this is unexpected. State information is:
{ error: 
   { [AssertionError: "ABC" == "pqr"]
     name: 'AssertionError',
     actual: 'ABC',
     expected: 'pqr',
     operator: '==',
     message: '"ABC" == "pqr"',
     domain: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        members: [] },
     domainThrown: true },
  previousResult: [],
  currentArguments: 
   [ { [AssertionError: "ABC" == "pqr"]
       name: 'AssertionError',
       actual: 'ABC',
       expected: 'pqr',
       operator: '==',
       message: '"ABC" == "pqr"',
       domain: [Object],
       domainThrown: true } ] }
    at Task.exit (/Users/balupton/Projects/taskgroup/out/lib/taskgroup.js:291:15)
    at Domain.emit (events.js:95:17)
    at process._fatalException (node.js:255:29)
```

**Comment by balupton** [comment] 2015-02-01 14:38
Is that what you got?

**Comment by kksharma1618** [comment] 2015-02-01 14:43
Can I see code for issue17.js?

**Comment by balupton** [comment] 2015-02-01 14:46
```
var TaskGroup = require('./').TaskGroup;
var Task = require('./').Task;
var assert = require('assert');

function toTest(a, next) {
	var tasks = new TaskGroup();
	tasks.addTask('upper case', function(next) {
		a = a.toUpperCase();
		next();
	});
	tasks.done(function(err) {
		next(err, a);
	}).run();
}
function toTest2(a, next) {
	var tasks = new TaskGroup();
	tasks.addTask('upper case', function(next) {
		a = a.toUpperCase();
		next();
	});
	tasks.done(function(err) {
		setTimeout(function() {
			next(err, a);
		});
	}).run();

}
function toTestWithoutTaskGroup(a, next) {
	a = a.toUpperCase();
	setTimeout(function() {
		next(null, a);
	}, 10);
}

toTest("abc", function(err, r) {
	assert.equal(r, "lmn");
});

toTest2("abc", function(err, r) {
	assert.equal(r, "pqr");
});


toTestWithoutTaskGroup("abc", function(err, r) {
	assert.equal(r, "efg");
});
```

Seems you've updated it, will try with your update.

**Comment by balupton** [comment] 2015-02-01 14:48
Distilled down to:

``` js
var TaskGroup = require('./').TaskGroup
var Task = require('./').Task
var assert = require('assert')

var tasks = new TaskGroup()
tasks.addTask('test', function(complete) {
	console.log('hello world')
	complete()
});
tasks.done(function(err) {
	throw new Error('goodbye world')
}).run()
```

**Comment by kksharma1618** [comment] 2015-02-01 14:52
yep. goodbye world error shouldnt be suppressed. ideal solution will be, like you said, to fix the domain. call done listeners outside of it.

**Comment by balupton** [comment] 2015-02-01 14:52
Seems domain doesn't have anything to do with it, disabling it did nothing.

**Comment by balupton** [comment] 2015-02-01 14:56
Weird output with:

```
var TaskGroup = require('./').TaskGroup
var Task = require('./').Task
var assert = require('assert')

var myTask = new Task(function(complete) {
	console.log('hello world')
	complete()
})
myTask.done(function(err) {
	throw new Error('goodbye world')
}).run()

setTimeout(function(){
	throw new Error("world still exists! this shouldn't have happend")
}, 1000)
```

Maybe there is a try catch somewhere.

**Comment by balupton** [comment] 2015-02-01 14:58
Found the cause, working on a fix. Leave it with me :-) :+1:

**Comment by kksharma1618** [comment] 2015-02-01 15:03
great. thanks :)

**Comment by balupton** [comment] 2015-02-01 15:37
Got a fix locally, but really tired and it has a minor breaking change. Will sleep on it and release tomorrow.

**Comment by balupton** [comment] 2015-02-01 20:52
So the issue was actually being called by the try...catch that was used, AS well as the domain - hence why disabling domains still caused the issue. This is also why the nextTick workaround worked, as it killed the scope.

I've fixed it by removing the try...catch and limiting the scope of the domain to just where it is needed as well as manually exiting it upon task method completion.

Fix will be in v4.1.0. Releasing now.

**Comment by balupton** [comment] 2015-02-01 20:57
Released.

**Closed** 2015-02-01 21:09 UTC
Labels: bug

**Comment by balupton** [comment] 2015-02-02 02:43
Ended up releasing v4.2.0 that has try catch still in it, but uses your next tick idea :-) As it was needed for node 0.8 and browser compat

**Comment by kksharma1618** [comment] 2015-02-02 03:11
Thanks for the fix. Just updated and tried again. Works.

Cool library btw, I was using async before this. Just switched to taskgroup in this project. I really like how you implemented taskgroup.

**Comment by pflannery** [comment] 2015-02-09 12:12
just got latest from master and running the tests with node 0.12.0 give this error

```
Error #1:
task > errors > it should not catch errors within the completion callback: issue 17
Error: Issue 17 check did not execute correctly
    at d:\dev\github\bevry\taskgroup\out\test\taskgroup-unit-test.js:216:19
    at d:\dev\github\bevry\taskgroup\node_modules\safeps\out\lib\safeps.js:247:47
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

**Comment by balupton** [comment] 2015-02-09 14:06
@pflannery I'll check it out, strange as I tested it with 0.11 and iojs and worked fine
